config/routes.rb
Rails.application.routes.draw do
  
  resources :rooms, only: %i[show]

  resources :profiles

  resources :articles do
    resources :article_likes, only: [:create, :destroy]
    resources :requests, only: [:create, :update, :destroy]
  end

  root "statics#top"

  devise_for :users, controllers: {   registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
end

app/models/article.rb
class Article < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :user

    has_many :article_likes, dependent: :destroy
    has_many :article_liked_users, through: :article_likes, source: :user

    has_many :requests, dependent: :destroy
    has_many :requested_users, through: :requests, source: :user

    has_one :room, dependent: :destroy
    accepts_nested_attributes_for :room
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    if params[:search] == nil
      @articles = Article.all.page(params[:page]).per(10)
    elsif params[:search] == ''
      @articles = Article.all.page(params[:page]).per(10)
    else
      @articles = Article.where("title LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(10)
                  .or(Article.where("content LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(10))
                  .or(Article.where("to_join LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(10))
                  .or(Article.where("skill LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(10))
                  .or(Article.where("category LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(10))
                  .or(Article.where(user_id: Profile.where("univercity LIKE ? ",'%' + params[:search] + '%')).page(params[:page]).per(10))
                  .or(Article.where(user_id: Profile.where("faculty LIKE ? ",'%' + params[:search] + '%')).page(params[:page]).per(10))
                  .or(Article.where(user_id: Profile.where("department LIKE ? ",'%' + params[:search] + '%')).page(params[:page]).per(10))
    end
  end

  def show
    @article = Article.find(params[:id])
    @article_like = ArticleLike.new
    @request = Request.new
    @request_user = Request.find_by(user_id: current_user.id, article_id: @article.id)
    @requested = Request.where(article_id: params[:id])
    @requested_user = User.where(id: @requested.pluck(:user_id))
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update 
    @article= Article.find(params[:id])
    if @article.update(article_params)
      redirect_to :action => "show", :id => @article.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to action: :index
  end
  
  def new
    @article = Article.new
    @article.build_room
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.build_room
    if @article.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  private

  def article_params
    params.require(:article).permit(:category, :title, :image ,:content, :to_join, :skill)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_room.html.erb
<% Request.where(user_id: current_user.id).each do |user| %>
    <% if user.user_id == current_user.id && user.permission == true %>
        <li><%= link_to Article.find(user.article_id).title, room_path(user.article_id),data: {"turbolinks" => false} %></li>
    <% end %>
<% end %>
<% Article.where(user_id: current_user.id).each do |mine| %>
    <li><%= link_to mine.title+" (my post)", room_path(mine.id),data: {"turbolinks" => false} %></li>
<% end %>

app/views/articles/edit.html.erb
<%= stylesheet_link_tag "articles/style", :media => "all" %>
<div class="wrapper">
    <main>
    <!-- サイドバー -->
        <div class="sidebar">
            <button class="nav_toggle">
                <i></i>
                <i></i>
                <i></i>
            </button>
            <div class="nav">
                <%= link_to image_tag("logo.png",width:"60px",alt:"ロゴ",class:"logo"), root_path %>
                <%= form_tag({controller:"articles",action:"index"}, method: :get, class:"search") do %>
                    <%= text_field_tag :search, "", {class: "form_size", placeholder: "Enter a keyword"} %>
                    <%= button_tag type: "submit" do %><i class="fas fa-search"></i><% end %>
                <% end %>
                <button><%= link_to "MY PAGE" , profile_path(current_user.id),class:"new_btn" %></button>
                <button><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete ,class: "new_btn"%></button>
                <h3>MY ROOM</h3>
                <div class="container">
                    <ul class="rooms">
                        <%= render 'room' %>
                    </ul>
                </div>
                <br>
                <button><%= link_to "ALL PAGE", articles_path, class: "new_btn" %></button>
                <br>
                <h4 class="search_head">SEARCH</h4>
                <div class="category_search">
                    <h4>CATEGORY</h4>
                    <ul>
                        <li><%= button_to "スキルアップ", {controller: "articles", action: "index"}, { method: :get, params: {search: 'SKILL'} } %></li>
                        <li><%= button_to "チャレンジ", {controller: "articles", action: "index"}, { method: :get, params: {search: 'CHALLENGE'} } %></li>
                        <li><%= button_to "ヘルプ", {controller: "articles", action: "index"}, { method: :get, params: {search: 'HELP'} } %></li>
                    </ul>
                    <h4>UNIVERSITY</h4>
                    <ul>
                        <% Profile.pluck("univercity").reject(&:blank?).uniq.first(5).each do |u| %>
                            <li><%= button_to u, {controller: "articles", action: "index"}, { method: :get, params: {search: u} } %></li>
                        <% end %>
                        <% if Profile.pluck("univercity").reject(&:blank?).uniq[5] != nil %>
                            <details>
                                <summary>more</summary>
                                <div class="details_content">
                                    <% Profile.pluck("univercity").reject(&:blank?).uniq[5..-1].each do |u| %>
                                        <li><%= button_to u, {controller: "articles", action: "index"}, { method: :get, params: {search: u} } %></li>
                                    <% end %>
                                </div>
                            </details>
                        <% end %>
                    </ul>
                    <h4>FACULTY</h4>
                    <ul>
                        <% Profile.pluck("faculty").reject(&:blank?).uniq.first(5).each do |f| %>
                            <li><%= button_to f, {controller: "articles", action: "index"}, { method: :get, params: {search: f} } %></li>
                        <% end %>
                        <% if Profile.pluck("faculty").reject(&:blank?).uniq[5] != nil %>
                            <details>
                                <summary>more</summary>
                                <div class="details_content">
                                    <% Profile.pluck("faculty").reject(&:blank?).uniq[5..-1].each do |f| %>
                                        <li><%= button_to f, {controller: "articles", action: "index"}, { method: :get, params: {search: f} } %></li>
                                    <% end %>
                                </div>
                            </details>
                        <% end %>
                    </ul>
                    <h4>DEPARTMENT</h4>
                    <ul>
                        <% Profile.pluck("department").reject(&:blank?).uniq.first(5).each do |d| %>
                            <li><%= button_to d, {controller: "articles", action: "index"}, { method: :get, params: {search: d} } %></li>
                        <% end %>
                        <% if Profile.pluck("department").reject(&:blank?).uniq[5] != nil %>
                            <details>
                                <summary>more</summary>
                                <div class="details_content">
                                    <% Profile.pluck("department").reject(&:blank?).uniq[5..-1].each do |d| %>
                                        <li><%= button_to d, {controller: "articles", action: "index"}, { method: :get, params: {search: d} } %></li>
                                    <% end %>
                                </div>
                            </details>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    <!-- メインコンテンツ -->
        <div class="topic">
            <% if @article.category="SKILL" %>
                <%= image_tag 'category/skill.jpg', id:"headImg", class:"head_img", alt:"カテゴリ" %>
            <% elsif @article.category="CHALLENGE" %>
                <%= image_tag 'category/challenge.jpg', id:"headImg", class:"head_img", alt:"カテゴリ" %>
            <% elsif @article.category="HELP" %>
                <%= image_tag 'category/help.jpg', id:"headImg", class:"head_img", alt:"カテゴリ" %>
            <% else %>
                <%= image_tag "no-img.png", id:"headImg", class:"head_img", alt:"カテゴリ" %>
            <% end %>
            <div class="back">
                <div class="content">
                    <div class="title2">
                        <%= form_for @article do |f| %>
                        <div class="category_tab">
                            <p>CATEGORY<br>
                                <%= f.select :category, [["SKILL", "SKILL"], ["CHALLENGE", "CHALLENGE"], ["HELP", "HELP"]], {include_blank: "選択して下さい"} , {:onchange => 'image_change(this.selectedIndex)'} %>
                            </p>
                        </div>
                        <div class="type_title">
                            <p>TITLE</p>
                            <%= f.text_area :title, wrap:"hard", :placeholder => "タイトルを入力してください" %>
                        </div>
                        <div class="sel_image">
                            <p>IMAGE</p>
                            <label>
                                結果イメージの画像を選択してください
                                <%= f.file_field :image, onchange:"previewImage(this)" %>
                            </label>
                        </div>
                        <% if @article.image? %>
                            <%= image_tag @article.image.to_s, id:"preview", alt:"プレビュー",size: '300x200'%>
                        <% else %>
                            <%= image_tag "no-img.png", id:"preview", alt:"画像なし", size: '300x200' %>
                        <% end %>
                        <div class="type_content">
                            <p>CONTENT</p>
                            <%= f.text_area :content, wrap:"hard", :placeholder => "内容を入力してください" %>
                        </div>
                        <div class="type_conditions">
                            <p>TO JOIN</p>
                            <%= f.text_area :to_join, wrap:"hard", :placeholder => "応募条件を入力してください" %>
                        </div>
                        <div class="type_skill">
                            <p>SKILL</p>
                            <%= f.text_area :skill, wrap:"hard", :placeholder => "参加することで習得できるスキルを入力してください" %>
                        </div>
                        <%= f.submit "POST", class:"post_btn" %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- フッター -->
    <footer>
        <small>© 2020 YutaToyomi</small>
        <ul class="sns_buttons">
            <li>
                <a rel="nofollow" href="http://twitter.com/share?text=【大学生のためのコミュニティサイト〇〇】&url=【URL】&hashtags=【〇〇】"
                    onclick="window.open(encodeURI(decodeURI(this.href)), 'tweet_window',
                    'width=600, height=470, toolbar=no, scrollbars=yes, resizable=yes'); return false;">
                    <i class="fa fa-twitter-square"></i>
                </a>
            </li>
            <li>
                <a rel="nofollow" href="http://www.facebook.com/share.php?text=【大学生のためのコミュニティサイト〇〇】&url=【URL】&hashtags=【〇〇】"
                    onclick="window.open(encodeURI(decodeURI(this.href)), 'facebook_window',
                    'width=600, height=470, toolbar=no, scrollbars=yes, resizable=yes'); return false;">
                    <i class="fa fa-facebook-square"></i>
                </a>
            </li>
            <li>
                <a rel="nofollow" href="http://line.me/R/msg/?【大学生のためのコミュニティサイト〇〇】url=【URL】"
                    onclick="window.open(encodeURI(decodeURI(this.href)), 'line_window',
                    'width=600, height=470, toolbar=no, scrollbars=yes, resizable=yes'); return false;">
                    <i class="fab fa-line"></i>
                </a>
            </li>
        </ul>
    </footer>
</div>
<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>

<%= javascript_pack_tag 'js/func', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'js/image', 'data-turbolinks-track': 'reload' %>

<script>
    let list_img = new Array();
    list_img[0] = new Array("<%= asset_path('no-img.png') %>");
    list_img[1] = new Array("<%= asset_path('category/skill.jpg') %>");
    list_img[3] = new Array("<%= asset_path('category/help.jpg') %>");
    list_img[2] = new Array("<%= asset_path('category/challenge.jpg') %>");
    let elem = document.getElementById("headImg")
    
    function image_change(sel_val){
        elem.setAttribute("src", list_img[sel_val]);
    }
</script>
<script>
    function previewImage(obj){
        var fileReader = new FileReader();
        fileReader.onload = (function() {
            document.getElementById('preview').src = fileReader.result;
        });
        fileReader.readAsDataURL(obj.files[0]);
    }
</script>

app/views/articles/index.html.erb
<%= stylesheet_link_tag "articles/style_show", :media => "all" %>
<div class="wrapper">
    <main>
    <!-- サイドバー -->
        <div class="sidebar">
            <button class="nav_toggle">
                <i></i>
                <i></i>
                <i></i>
            </button>
            <div class="nav">
                <%= link_to image_tag("logo.png",width:"60px",alt:"ロゴ",class:"logo"), root_path %>
                <%= form_tag({controller:"articles",action:"index"}, method: :get, class:"search") do %>
                    <%= text_field_tag :search, "", {class: "form_size", placeholder: "Enter a keyword"} %>
                    <%= button_tag type: "submit" do %><i class="fas fa-search"></i><% end %>
                <% end %>
                <button><%= link_to "MY PAGE" , profile_path(current_user.id), class:"new_btn" %></button>
                <button><%= link_to"POST" , new_article_path,class:"new_btn" %></button>
                <button><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete ,class: "new_btn"%></button>
                <h3>MY ROOM</h3>
                <div class="container">
                    <ul class="rooms">
                        <%= render 'room' %>
                    </ul>
                </div>
                <br>
                <% if params[:search] == nil or params[:search] == "" %>
                <% else %>
                    <button><%= link_to "ALL PAGE", articles_path, class: "new_btn" %></button>
                <% end %>
                <br>
                <h4 class="search_head">SEARCH</h4>
                <div class="category_search">
                    <h4>CATEGORY</h4>
                    <ul>
                        <li><%= button_to "スキルアップ", {controller: "articles", action: "index"}, { method: :get, params: {search: 'SKILL'} } %></li>
                        <li><%= button_to "チャレンジ", {controller: "articles", action: "index"}, { method: :get, params: {search: 'CHALLENGE'} } %></li>
                        <li><%= button_to "ヘルプ", {controller: "articles", action: "index"}, { method: :get, params: {search: 'HELP'} } %></li>
                    </ul>
                    <h4>UNIVERSITY</h4>
                    <ul>
                        <% Profile.pluck("univercity").reject(&:blank?).uniq.first(5).each do |u| %>
                            <li><%= button_to u, {controller: "articles", action: "index"}, { method: :get, params: {search: u} } %></li>
                        <% end %>
                        <% if Profile.pluck("univercity").reject(&:blank?).uniq[5] != nil %>
                            <details>
                                <summary>more</summary>
                                <div class="details_content">
                                    <% Profile.pluck("univercity").reject(&:blank?).uniq[5..-1].each do |u| %>
                                        <li><%= button_to u, {controller: "articles", action: "index"}, { method: :get, params: {search: u} } %></li>
                                    <% end %>
                                </div>
                            </details>
                        <% end %>
                    </ul>
                    <h4>FACULTY</h4>
                    <ul>
                        <% Profile.pluck("faculty").reject(&:blank?).uniq.first(5).each do |f| %>
                            <li><%= button_to f, {controller: "articles", action: "index"}, { method: :get, params: {search: f} } %></li>
                        <% end %>
                        <% if Profile.pluck("faculty").reject(&:blank?).uniq[5] != nil %>
                            <details>
                                <summary>more</summary>
                                <div class="details_content">
                                    <% Profile.pluck("faculty").reject(&:blank?).uniq[5..-1].each do |f| %>
                                        <li><%= button_to f, {controller: "articles", action: "index"}, { method: :get, params: {search: f} } %></li>
                                    <% end %>
                                </div>
                            </details>
                        <% end %>
                    </ul>
                    <h4>DEPARTMENT</h4>
                    <ul>
                        <% Profile.pluck("department").reject(&:blank?).uniq.first(5).each do |d| %>
                            <li><%= button_to d, {controller: "articles", action: "index"}, { method: :get, params: {search: d} } %></li>
                        <% end %>
                        <% if Profile.pluck("department").reject(&:blank?).uniq[5] != nil %>
                            <details>
                                <summary>more</summary>
                                <div class="details_content">
                                    <% Profile.pluck("department").reject(&:blank?).uniq[5..-1].each do |d| %>
                                        <li><%= button_to d, {controller: "articles", action: "index"}, { method: :get, params: {search: d} } %></li>
                                    <% end %>
                                </div>
                            </details>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    <!-- メインコンテンツ -->
        <div class="topic">
            <% if params[:search] == nil %>
                <h1>ALL TOPIC</h1>
            <% elsif params[:search] == "" %>
                <h1>ALL TOPIC</h1>
            <% else %>
                <h1><%= "「"+ params[:search] + "」" + "の検索結果" %></h1>
            <% end %>
            <% @articles.each do |t| %>
            <div class="post">
                <% if t.image_url == nil then %>
                    <%= link_to image_tag("no-img.png",class:"post-img", alt:"画像がありません"), article_path(t.id) %>
                <% else %>
                    <%= link_to image_tag(t.image_url,class:"post-img", alt:"最終イメージ"), article_path(t.id) %>
                <% end %>
                <div class="conhesive">
                    <h2><%= t.title %></h2>
                    <div class="explain">
                        <div class="content">
                            <h4>CONTENT</h4>
                            <p><%= safe_join(t.content.to_s.split("\n"), tag(:br)) %></p>
                        </div>
                        <div class="conditions">
                            <h4>TO JOIN</h4>
                            <p><%= safe_join(t.to_join.to_s.split("\n"), tag(:br)) %></p>
                        </div>
                        <div class="skill">
                            <h4>SKILL</h4>
                            <p><%= safe_join(t.skill.to_s.split("\n"), tag(:br)) %></p>
                        </div>
                    </div>
                    <div class="btns">
                        <% if current_user.already_liked?(t) %>
                            <%=link_to article_article_like_path(id: t.id, article_id: t.id), method: :delete do%>
                                <i class="fas fa-heart"></i>
                            <%=t.article_likes.count%>
                            <%end%>
                        <% else %>
                            <%=link_to article_article_likes_path(id: t.id, article_id: t.id), method: :post do%>
                                <i class="far fa-heart"></i>
                            <%=t.article_likes.count%>
                            <%end%>
                        <% end %>
                        
                        <button><%= link_to "by: "+ Profile.find_by(user_id: t.user_id).name ,profile_path(t.user.id), id:"more_btn" %></button>

                        <button><%= link_to"詳細" ,article_path(t.id), id:"more_btn" %></button>
                        <% if current_user.id == t.user_id %>
                            <button><%= link_to"編集" ,edit_article_path(t.id), id:"more_btn" %></button>
                            <button><%= link_to"削除" ,article_path(t.id), method: :delete , id:"more_btn" %></button>
                        <% end %>
                    </div>
                </div>
            </div>   
            <% end %>
            <%= paginate @articles %>
        </div>
    </main>  
    <!-- フッター -->
    <footer>
        <small>© 2020 YutaToyomi</small>
        <ul class="sns_buttons">
            <li>
                <a rel="nofollow" href="http://twitter.com/share?text=【大学生のためのコミュニティサイト〇〇】&url=【URL】&hashtags=【〇〇】"
                    onclick="window.open(encodeURI(decodeURI(this.href)), 'tweet_window',
                    'width=600, height=470, toolbar=no, scrollbars=yes, resizable=yes'); return false;">
                    <i class="fa fa-twitter-square"></i>
                </a>
            </li>
            <li>
                <a rel="nofollow" href="http://www.facebook.com/share.php?text=【大学生のためのコミュニティサイト〇〇】&url=【URL】&hashtags=【〇〇】"
                    onclick="window.open(encodeURI(decodeURI(this.href)), 'facebook_window',
                    'width=600, height=470, toolbar=no, scrollbars=yes, resizable=yes'); return false;">
                    <i class="fa fa-facebook-square"></i>
                </a>
            </li>
            <li>
                <a rel="nofollow" href="http://line.me/R/msg/?【大学生のためのコミュニティサイト〇〇】url=【URL】"
                    onclick="window.open(encodeURI(decodeURI(this.href)), 'line_window',
                    'width=600, height=470, toolbar=no, scrollbars=yes, resizable=yes'); return false;">
                    <i class="fab fa-line"></i>
                </a>
            </li>
        </ul>
    </footer>
</div>

<%= javascript_pack_tag 'js/func' %>

<script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>